//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _MFCONSOLEAPPLICATION1_H_
#define _MFCONSOLEAPPLICATION1_H_

#include <TinyCLR_Interop.h>
struct Library_MFConsoleApplication1_MFConsoleApplication1_Resources
{
    static const int FIELD_STATIC__manager = 0;


    //--//

};

struct Library_MFConsoleApplication1_SprinklerControl_Program
{
    static const int FIELD_STATIC__LED = 1;


    //--//

};

struct Library_MFConsoleApplication1_SprinklerControl_SprinklerConfig
{
    static const int FIELD__sysEnabled = 1;
    static const int FIELD__numZones = 2;
    static const int FIELD__durationMinutes = 3;
    static const int FIELD__offsetMinutes = 4;
    static const int FIELD__startTimeInMinutes = 5;
    static const int FIELD__endTimeInMinutes = 6;
    static const int FIELD__zoneValves = 7;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_MFConsoleApplication1;

#endif  //_MFCONSOLEAPPLICATION1_H_
