//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SPRINKLERCONTROL_H_
#define _SPRINKLERCONTROL_H_

#include <TinyCLR_Interop.h>
struct Library_SprinklerControl_SprinklerControl_TCPServer
{
    static const int FIELD__server = 1;


    //--//

};

struct Library_SprinklerControl_SprinklerControl_TCPServer__ProcessClientRequest
{
    static const int FIELD__m_clientSocket = 1;


    //--//

};

struct Library_SprinklerControl_SprinklerControl_Program
{
    static const int FIELD_STATIC__sprinklerConfig = 0;
    static const int FIELD_STATIC__server = 1;


    //--//

};

struct Library_SprinklerControl_SprinklerControl_Resources
{
    static const int FIELD_STATIC__manager = 2;


    //--//

};

struct Library_SprinklerControl_SprinklerControl_SprinklerConfig
{
    static const int FIELD__sysEnabled = 1;
    static const int FIELD__numZones = 2;
    static const int FIELD__durationMinutes = 3;
    static const int FIELD__offsetMinutes = 4;
    static const int FIELD__startTimeInMinutes = 5;
    static const int FIELD__endTimeInMinutes = 6;
    static const int FIELD__zoneValves = 7;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SprinklerControl;

#endif  //_SPRINKLERCONTROL_H_
